import os
import json
from dotenv import load_dotenv
from google import genai
from app.schemas.command import CommandIntent
from app.services.capability_registry import CapabilityRegistry
from app.services.command_catalog_service import CommandCatalogService

load_dotenv()

def sanitize_and_fix_placeholders(cmd: str) -> str:
    """Removes invalid placeholders like /path/to/ and makes paths locally runnable."""
    fixed = cmd.strip()
    
    if "/path/to/" in fixed:
        fixed = fixed.replace("/path/to/", "./")
    if "/path/to" in fixed:
        fixed = fixed.replace("/path/to", ".")
        
    return fixed

class IntentService:
    @staticmethod
    async def interpret(natural_request: str) -> CommandIntent:
        req = natural_request.strip()
        
        # 1. Direct command lookup in capability registry
        routed = CapabilityRegistry.route_command(req)
        if routed:
            return routed

        # 2. LLM Translation
        api_key = os.getenv("GEMINI_API_KEY")
        if not api_key:
            sanitized = sanitize_and_fix_placeholders(req)
            routed = CapabilityRegistry.route_command(sanitized)
            if routed: return routed
            
            return CommandIntent(
                intent=f"Execute command '{sanitized}'",
                command=sanitized,
                arguments=sanitized.split()[1:] if len(sanitized.split()) > 1 else [],
                safety_level="SAFE",
                explanation="Deterministic heuristic translation (No LLM key required)."
            )

        try:
            client = genai.Client(api_key=api_key)
            system_prompt = """You are a Principal Unix Systems Engineer and POSIX Shell translator.
Translate the user's natural language request into a valid, single-line POSIX-compliant shell command.

CRITICAL RULES:
1. NEVER use dummy placeholders like '/path/to/...', '<placeholder>', or non-existent absolute paths.
2. If creating files in a subfolder or directory, ALWAYS make sure the directory exists using 'mkdir -p <dir> && touch <dir>/<file>'.
3. Always generate clean, immediately runnable commands relative to the current working directory.

Respond ONLY with a valid JSON object matching this schema:
{
  "command": "The exact shell command without markdown"
}
Do not wrap response in markdown code blocks. Output plain JSON only."""

            response = client.models.generate_content(
                model="gemini-2.5-flash",
                contents=req,
                config=genai.types.GenerateContentConfig(
                    system_instruction=system_prompt,
                    temperature=0.0,
                    response_mime_type="application/json",
                ),
            )
            
            response_json = json.loads(response.text)
            raw_cmd = response_json.get("command", req)
            fixed_cmd = sanitize_and_fix_placeholders(raw_cmd)
            
            # Post-translation Capability check
            routed = CapabilityRegistry.route_command(fixed_cmd)
            if routed:
                return routed
            
            return CommandIntent(
                intent="Execute generated command",
                command=fixed_cmd,
                arguments=fixed_cmd.split()[1:] if len(fixed_cmd.split()) > 1 else [],
                safety_level="RISKY",
                explanation="Generated by LLM but not found in known capability catalog."
            )
            
        except Exception as e:
            sanitized = sanitize_and_fix_placeholders(req)
            return CommandIntent(
                intent=f"Execute: {sanitized}",
                command=sanitized,
                arguments=sanitized.split()[1:] if len(sanitized.split()) > 1 else [],
                safety_level="RISKY",
                explanation=f"Fallback translator used ({str(e)})"
            )
